// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaA_SolBooking.Datos;

namespace PruebaA_SolBooking.Migrations
{
    [DbContext(typeof(HotelContexto))]
    [Migration("20200929130632_Migracioninicial")]
    partial class Migracioninicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaA_SolBooking.Modelo.DetalleHotel", b =>
                {
                    b.Property<string>("Nombre")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caracteristicas");

                    b.Property<string>("Ciudad");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Imagen");

                    b.HasKey("Nombre");

                    b.ToTable("DetalleHotelItems");
                });

            modelBuilder.Entity("PruebaA_SolBooking.Modelo.Hotel", b =>
                {
                    b.Property<string>("Nombre")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Categoria");

                    b.Property<string>("Descripcion");

                    b.Property<bool>("Destacado");

                    b.Property<string>("Foto");

                    b.HasKey("Nombre");

                    b.ToTable("CabeceraHotelItems");
                });
#pragma warning restore 612, 618
        }
    }
}
